import { useEffect, useMemo, useState } from "react"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { FileText, Trash2, Search } from "lucide-react"
import { useCompany } from "../context/CompanyContext"
import { useBreadcrumbs } from "../context/BreadcrumbContext"
import { queryKeys } from "../lib/queryKeys"
import { researchApi } from "../api/research"
import type { ResearchReport } from "../api/research"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { EmptyState } from "../components/EmptyState"
import { PageSkeleton } from "../components/PageSkeleton"

const BULLISH = new Set(["buy", "strong_buy", "overweight"])
const BEARISH = new Set(["sell", "strong_sell", "underweight"])

function recommendationBadge(recommendation: string) {
  const key = recommendation.trim().toLowerCase()
  if (BULLISH.has(key)) {
    return (
      <Badge variant="default" className="bg-green-600 hover:bg-green-600 text-white">
        {recommendation}
      </Badge>
    )
  }
  if (BEARISH.has(key)) {
    return <Badge variant="destructive">{recommendation}</Badge>
  }
  return <Badge variant="secondary">{recommendation}</Badge>
}

function ReportCard({ report, onDelete }: { report: ResearchReport; onDelete: () => void }) {
  return (
    <div className="rounded-lg border border-border bg-card p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-mono font-bold text-sm">{report.ticker}</span>
          <Badge variant="secondary">{report.reportType}</Badge>
          {report.recommendation && recommendationBadge(report.recommendation)}
          {report.targetPriceCents != null && (
            <span className="text-sm tabular-nums text-foreground/90">
              ${(report.targetPriceCents / 100).toFixed(2)}
            </span>
          )}
          <span className="text-xs text-muted-foreground">
            {new Date(report.createdAt).toLocaleDateString()}
          </span>
        </div>
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={onDelete}
          aria-label={`Delete report for ${report.ticker}`}
          className="text-muted-foreground hover:text-destructive shrink-0"
        >
          <Trash2 className="h-3.5 w-3.5" />
        </Button>
      </div>
      <div className="text-sm whitespace-pre-wrap mt-2 text-foreground/90">{report.content}</div>
    </div>
  )
}

export function Reports() {
  const { selectedCompanyId } = useCompany()
  const { setBreadcrumbs } = useBreadcrumbs()
  const queryClient = useQueryClient()
  const [filter, setFilter] = useState("")

  useEffect(() => {
    setBreadcrumbs([{ label: "Reports" }])
  }, [setBreadcrumbs])

  const { data: reports, isLoading } = useQuery({
    queryKey: queryKeys.research.list(selectedCompanyId!),
    queryFn: () => researchApi.list(selectedCompanyId!),
    enabled: !!selectedCompanyId,
  })

  const deleteMutation = useMutation({
    mutationFn: (reportId: string) => researchApi.remove(selectedCompanyId!, reportId),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: queryKeys.research.list(selectedCompanyId!) }),
  })

  const filtered = useMemo(() => {
    if (!reports) return []
    const q = filter.trim().toUpperCase()
    if (!q) return reports
    return reports.filter((r) => r.ticker.toUpperCase().includes(q))
  }, [reports, filter])

  if (!selectedCompanyId)
    return <EmptyState icon={FileText} message="Select a workspace to view research reports." />
  if (isLoading) return <PageSkeleton />

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-xl font-semibold">Reports</h1>
        <p className="text-sm text-muted-foreground mt-0.5">Research reports generated by your analyst agents</p>
      </div>

      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Filter by ticker"
          value={filter}
          onChange={(e) => setFilter(e.target.value.toUpperCase())}
          className="font-mono pl-9"
          maxLength={20}
        />
      </div>

      {(reports?.length ?? 0) === 0 ? (
        <EmptyState
          icon={FileText}
          message="No research reports yet. Your analyst agents will generate reports here."
        />
      ) : filtered.length === 0 ? (
        <EmptyState icon={FileText} message="No reports match this ticker." />
      ) : (
        <div className="space-y-3">
          {filtered.map((report) => (
            <ReportCard
              key={report.id}
              report={report}
              onDelete={() => deleteMutation.mutate(report.id)}
            />
          ))}
        </div>
      )}
    </div>
  )
}
